### ISSUE TITLE
Error Installing IntelMQ Manager

### ISSUE THREAD

**Issue by mf370** [certtools/intelmq-manager#104]
I tried to install IntelMQ Manager on a CentOS 7 using this package: https://software.opensuse.org//download.html?project=home%3Asebix%3Aintelmq&package=intelmq-manager

However, it gave me the following error: 
```
Transaction check error:
  file /etc/sudoers.d from install of intelmq-manager-0.2-6.1.noarch conflicts with file from package sudo-1.8.6p7-20.el7.x86_64
```
I'm not sure if this is caused by the version of the CentOS that I'm using, or if it is something else.

**Comment by wagner-certat** [comment]
Thanks for reporting this. I applied some changes concerning the directories and files to the specfile. The new packages are currently being processed at the build system.

You can watch the build progress here on the right side: https://build.opensuse.org/project/show/home:sebix:intelmq

However I was unable to use the manager to manage the installation. CentOS seems to be a bit tricky. I get errors when saving the configuration (permission errors) and reading the status (management, monitor), also permission problems. I can't solve this CentOS problems myself :/
intelMQ itself works fine as far as I see.

**Comment by mf370** [comment]
Do you think that this package might work on a RedHat? Or it will be similar to CentOS?

**Comment by wagner-certat** [comment]
I think it will be same. I appreciate any help with these systems!

**Comment by mf370** [comment]
Alright! I'm new to CentOS, and I started using it last week... but first I'm trying to solve this issue first  [#981](https://github.com/certtools/intelmq/issues/981), if I make it, I'll let you know :)

**Comment by wagner-certat** [comment]
The should be fixes, right?

**Comment by mf370** [comment]
I haven't tried this package since it was updated / changed.
