### ISSUE TITLE
Configuration not showing.

### ISSUE THREAD

**Issue by SparkyNZL** [certtools/intelmq-manager#109]
Hi, 

I have installed the IntelMQ-Manager as per the documentation and everything seems to operate fine apart from the configuration manager all i ever get is the following, ive checked permissions groups and users and they are all as stated, am i missing something or is that are broken at present ?

Cheers.

------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/17818264/26854010-744fadb0-4b68-11e7-9b3a-531b2e7ae696.png)

**Comment by chorsley** [comment]
I ran into a similar issue recently, and for me it was making sure that the config.php file and sudoers file reflected the actual location of intelmqctl, as per https://github.com/certtools/intelmq-manager/blob/master/docs/INSTALL.md#ubuntu-1404--debian-8-1. Mine was under /opt/intelmq - it will depend on how you installed it.

**Comment by wagner-certat** [comment]
@SparkyNZL What OS are you using? How did you install it?

**Comment by SparkyNZL** [comment]
Thanks for your reply, intelmq seems to work fine, it's just the
intelmq-manager config issue. I'll have another look at the sudoers file
and make sure I haven't fat fingered anything .

OS is Ubuntu 16.04

Cheers

**Comment by wagner-certat** [comment]
The configuration page does not access intelmqctl at all, so it's not related to the sudoers file.

Again: How did you install intelmq-manager?

Can the webserver access the files (on the shell)?

**Comment by SparkyNZL** [comment]
Just the usual, git clone, this is the fourth one I've setup. Www-data is a
member of the intelmq group .

I know I must be missing something but I can't see the woods for the trees
.. I'll look at it in the morning and see what I can come up with. Thanks
for your help ;)



Sent from my spaceship...

On 7/06/2017 8:54 PM, "Wagner" <notifications@github.com> wrote:

The configuration page does not access intelmqctl at all, so it's not
related to the sudoers file.

Again: How did you install intelmq-manager?

Can the webserver access the files (on the shell)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/certtools/intelmq-manager/issues/109#issuecomment-306733256>,
or mute the thread

**Comment by SparkyNZL** [comment]
OK so there is a bug in pipeline.js

there is a missing "}"

This is stopping the configuration from loading

-------------------------------------------------------------------------------

if (edge['destination-queues'].length == 0) {
            edge['destination-queues'] = undefined;
        } else {
            edge['destination-queues'].sort()
        edge = sortObjectByPropertyName(edge)
    }

---------------------------------------------------------------------------------------------------------

if (edge['destination-queues'].length == 0) {
            edge['destination-queues'] = undefined;
        } else {
            edge['destination-queues'].sort()
        edge = sortObjectByPropertyName(edge)
    }
}

--------------------------------------------------------------------------------------------------------------

**Comment by wagner-certat** [comment]
I thought I already fixed that -.-

Thanks!
