### ISSUE TITLE
Missing copyright notices

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq-manager#140]
No files except those in debian/ have copyright notices, see https://reuse.software/#two

**Comment by dmth** [comment]
It might make sense to update the "developers guide" https://github.com/certtools/intelmq/blob/develop/docs/Developers-Guide.md#license-and-author-files in order to allow listing of the license and the authors within the code-files:

> License and authors must be only listed in an external file but not inside the code files.

**Comment by wagner-certat** [comment]
The dev guide should certainly be adapted after we know how to deal with these issues. But probably after we know more about this stuff? :)

**Comment by wagner-certat** [comment]
licenses are declared in debian/copyright and LICENSES/ now. Dev guide has been updated in ab573db4efc84f6de4aa13315e1ff619d3bfe64e
Moving this to the next version
