### ISSUE TITLE
Error when saving a configuration with over 30 bots in docker image

### ISSUE THREAD

**Issue by michaelb20** [certtools/intelmq-manager#160]
I can edit my configuration and save it successfully. However, at the 30th bot the following error message appears.
![screenshot from 2018-06-15 19-43-13](https://user-images.githubusercontent.com/26380375/41482051-8dbe1a24-70d4-11e8-9a4f-277b8c5355ac.png)
If I edit the `runtime.conf` and `pipeline.conf` outside the manager it is displayed correctly, no errors appear at `intelmqctl check` and there are no error messages on the check interface. 
![screenshot from 2018-06-15 19-50-08](https://user-images.githubusercontent.com/26380375/41482266-55dd3472-70d5-11e8-87f1-6995ce3bb7c1.png)

The system can run normally, without errors. If I want to save the existing current version of the `*.conf`-Files without changes on the Manager it always comes to this error.

**Comment by sebix** [comment]
I found these lines in the error log of the apache in your docker container:
```
[Tue Jul 24 21:29:05.159846 2018] [:error] [pid 22] [client 10.94.0.1:51158] PHP Warning:  Unknown: Unable to create temporary file, Check permissions in temporary files directory. in Unknown on line 0, referer: http://localhost:8080/?page=configs
[Tue Jul 24 21:29:05.159886 2018] [:error] [pid 22] [client 10.94.0.1:51158] PHP Warning:  Unknown: POST data can't be buffered; all data discarded in Unknown on line 0, referer: http://localhost:8080/?page=configs
```

Looks very much like an apache2 configuration issue.

**Comment by wagner-certat** [comment]
I found these lines in the error log of the apache in your docker container:
```
[Tue Jul 24 21:29:05.159846 2018] [:error] [pid 22] [client 10.94.0.1:51158] PHP Warning:  Unknown: Unable to create temporary file, Check permissions in temporary files directory. in Unknown on line 0, referer: http://localhost:8080/?page=configs
[Tue Jul 24 21:29:05.159886 2018] [:error] [pid 22] [client 10.94.0.1:51158] PHP Warning:  Unknown: POST data can't be buffered; all data discarded in Unknown on line 0, referer: http://localhost:8080/?page=configs
```

Looks very much like an apache2 configuration issue.

**Comment by michaelb20** [comment]
Thanks for the advice! I've tried some stuff but can't get to the faulty configuration you mentioned. The permissions in the directories match those specified in the installation instructions. 
```
root@d5622671fb32:/var/log/apache2# ls -la /opt/intelmq/etc/
total 120
drwxrwxrwx 1 intelmq www-data  4096 Jul 25 12:38 .
drwxrwxrwx 1 intelmq www-data  4096 Jul 25 12:48 ..
-rwxrwxrwx 1 intelmq www-data  9866 Jul 25 12:37 BOTS
-rwxrwxrwx 1 intelmq www-data  1110 Jul 19 16:20 defaults.conf
-rwxrwxrwx 1 intelmq www-data 20533 Jul 18 09:51 harmonization.conf
drwxrwxrwx 1 intelmq www-data  4096 Jul 18 09:52 manager
-rwxrwxrwx 1 intelmq www-data  7898 Jul 25 12:37 pipeline.conf
-rwxrwxrwx 1 intelmq www-data 31820 Jul 25 12:59 runtime.conf
```
Even if I couldn't identify the temporary files directory `Unkown` (as it is referred to in the error log but it can only be `/tmp` or `/opt/intelmq/etc`, I would assume.), i tried a different approach: 

After commenting out the check [1] as you mentioned above, the POST with the various configurations from I get a `success` response and the message is also correct how it is sent. Now all *config* files are saved successfully. 

[1]https://github.com/certtools/intelmq-manager/blob/a9a118db002111043725fd3362a7779a063f54ee/intelmq-manager/php/save.php#L18

All right, all right!
But now the `runtime.conf` is growing again and at some point only all other configurations can be saved, because these differ considerably in the file size. 

in my case, that would be :
* `runtime.conf`: ~ **30 KB**
* `positions.conf`: ~ 4 KB
* `pipeline.conf`: ~ 8 KB 

As you have already found, there are probably problems with the buffer size of POST, which discards the complete content. Now the **`runtime.conf` file is completely empty**. The other files were transferred successfully! 

So I continued searching for the configuration problem with *apache* or *php*. However, I decided to experiment with the `php.ini` file to enlarge these buffers and to exclude errors. 

I made the following changes:

```
post_max_size = 1024M
memory_limit = 512M
upload_max_filesize = 1024M
```

But I did not succeed, so I am still looking for the problem or the solution however you wanna take it.

Please also correct me if I made false assumptions about the temporary directory, mentioned in the logs.

-----------------------------------------------------------------------------------------------------------

I also found another error message in the logs: (The only change in `save.php` was, the simple commenting out of the single line, as mentioned above)

```
[Wed Jul 25 12:58:35.418728 2018] [:error] [pid 34] [client 10.94.0.1:36970] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/php/save.php on line 22, referer: http://0.0.0.0:8080/?page=configs
```

**Comment by wagner-certat** [comment]
> Thanks for the advice! I've tried some stuff but can't get to the faulty configuration you mentioned. The permissions in the directories match those specified in the installation instructions.

The error does not originate from intelmq manager, but from your PHP installation. As far as I understand the error message, the temporary directory is not writeable _in your container_. This works everywhere else.

> As you have already found, there are probably problems with the buffer size of POST, which discards the complete content. Now the runtime.conf file is completely empty.

That is expected. The second error messages says that it discarded all data because of the first error. That's why the check is in place, which you deactivated.

**Comment by michaelb20** [comment]
According to the [manual installation instructions](https://github.com/certtools/intelmq-manager/blob/master/docs/INSTALL.md#manually), the permissions must be set for the directories 
*  `/opt/intelmq/etc/` or for the included conf files
* `/var/www/html/`

But as you can easily determine with 
```php
ini_get('upload_tmp_dir') ? ini_get('upload_tmp_dir') : sys_get_temp_dir();
```
, this `Unknown` directory is simply `/tmp` and these permissions must of course also be set in the course of the IntelMQ-Manager installation. 

---------------------------------------------------------------------------------------

```
chown intelmq:www-data /tmp
chmod g+w /tmp 
```

Thanks for your answers and for taking the time to take a closer look at the issue. I think it can be closed now.

**Comment by michaelb20** [comment]
According to the [manual installation instructions](https://github.com/certtools/intelmq-manager/blob/master/docs/INSTALL.md#manually), the permissions must be set for the directories 
*  `/opt/intelmq/etc/` or for the included conf files
* `/var/www/html/`

But as you can easily determine with 
```php
ini_get('upload_tmp_dir') ? ini_get('upload_tmp_dir') : sys_get_temp_dir();
```
, this `Unknown` directory is simply `/tmp` and these permissions must of course also be set in the course of the IntelMQ-Manager installation. 

---------------------------------------------------------------------------------------
In the example of my docker container, these were be the additional commands to fix this issue (if this error also occurs to someone else):
```
chown intelmq:www-data /tmp 
chmod g+w /tmp 
```

@wagner-certat: Thanks for your answers and for taking the time to take a closer look at the issue. I think it can be closed now.

**Comment by wagner-certat** [comment]
I suggest to report this issue at docker or whoever created this image. I will also add a hint about this in the docs.

**Comment by wagner-certat** [comment]
Addendum

> In the example of my docker container, these were the additional commands to fix this issue (if this error also occurs to someone else):
```
chown intelmq:www-data /tmp 
chmod g+w /tmp 
```

IntelMQ (Manager) does not need /tmp, your webserver does. But /tmp is a linux standard since ages anyway and we can rely on it.
