### ISSUE TITLE
Make location of intelmq/etc configurable

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq-manager#193]
Right now if someone uses the Debian packages the path
`/opt/intelmq/etc/` is changed to `/etc/intelmq` 
see https://github.com/certtools/intelmq-manager/blob/develop/debian/patches/fix-paths.patch

If someone wants to use the deb package for an IntelMQ development which is installed on `/opt/intelmq`
or otherwise someone wants to switch to an IntelMQ Manager in development mode, it would be cool to make the path configurable at runtime (if possible).

**Comment by wagner-certat** [comment]
Already the case for IntelMQ itself. (`INTELMQ_ROOT_DIR` env variable). I worked on IntelMQ Manager now to respect this too
