### ISSUE TITLE
Update documentation for new python backend

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq-manager#199]
See #197

**Comment by dominik335** [comment]
Any ETA on that?

**Comment by wagner-certat** [comment]
No, but contributions are welcome - as always :)

**Comment by wagner-certat** [comment]
https://github.com/certtools/intelmq-manager/issues/80#issuecomment-644655065

**Comment by schacht-certat** [comment]
The Python based "backend" is now a separate project called `intelmq-api` and living in https://github.com/certtools/intelmq-api. It is also documented there how to use it.

**Comment by wagner-certat** [comment]
The INSTALL.md document still only refers to the PHP backend. There are also no instructions about the use of a webserver with the new backend (in neither repository)

**Comment by wagner-certat** [comment]
Documentation has been moved to https://intelmq.readthedocs.io/en/latest/user/intelmq-api.html and https://intelmq.readthedocs.io/en/latest/user/intelmq-manager.html with a47032200dfe4646fe87844d4a8329cacde44fae
