### ISSUE TITLE
Update contributors list, add .mailmap for git stats

### ISSUE THREAD

**Issue by bernhardreiter** [certtools/intelmq-manager#203]
The following call results (on branch `dev-csrf` hopefully to be merged soon)
show two things:
 * CONTRIBUTORS.md could use an upgrade, e.g. Edvard Rejthar has contributed more than one commit and is not in the file.
 * `.mailmap` can help to get the stats clarified (see `git help shortlog`)

```fish
git shortlog -s -n
   242  Sebastian Wagner
    63  Mauro Silva
    51  Arno Esterhammer
    50  Tomás Lima
    42  mauroasilva
    34  Edvard Rejthar
    33  Bernhard Herzog
    23  Sascha Wilde
    13  AaronK
    10  Bernhard Reiter
     8  Sebastian
     7  ondj
     7  synchroack
     6  Aaron Kaplan
     4  Bernhard E. Reiter
     2  Alexander J
     2  Mauro
     2  SyNchroAcK
     2  Sybil Ehrensberger
     2  Tomás
     2  root
     1  Chema García
     1  Filip Pokorny
     1  JesseBowling
     1  sbilly

```

**Comment by aaronkaplan** [comment]
> On 16.07.2020, at 11:38, Bernhard E. Reiter <notifications@github.com> wrote:
> 
> 
> The following call results (on branch dev-csrf hopefully to be merged soon)
> show two things:
> 
> 	• CONTRIBUTORS.md could use an upgrade, e.g. Edvard Rejthar has contributed more than one commit and is not in the file.

Agreed! How about adding all those people.
Just one remark: I think the number of commits would be not helpful to include there.

But yes! Always give credit where credit is due!

Thanks for noticing.

**Comment by bernhardreiter** [comment]
>  How about adding all those people. 

It may or may not be an idea to have some minimum requirement for becoming listed as contributor, e.g. one or two significant contributions (which could be in one commit or several ones). The background for the suggestion is that more credit should go to people that contribute more and that the maintenance cost of the contributor list should be reasonalbe. Apply the test:  if just fixing one unsignificant typo in a comment as pull request is enough to get a list entry, then doing the entry is more work than fixing the typo and people with more significant contributions are listed right next to that person. ;)


(Some of the listed names are the same person, this is why .maplist is needed.)

**Comment by aaronkaplan** [comment]
> On 16.07.2020, at 11:57, Bernhard E. Reiter <notifications@github.com> wrote:
> 
> 
> How about adding all those people.
> 
> It may or may not be an idea to have some minimum requirement for becoming listed as contributor, e.g. one or two significant contributions (which could be in one commit or several ones). The background for the suggestion is that more credit should go to people that contribute more and that the maintenance cost of the contributor list should be reasonalbe. Apply the test: if just fixing one unsignificant typo in a comment as pull request is enough to get a list entry, then doing the entry is more work than fixing the typo and people with more significant contributions are listed right next to that person. ;)
> 
> (Some of the listed names are the same person, this is why .maplist is needed.)

I know. I tend to rather say a "thank you" even if it's a minor contribution ...

Concerning duplicates - it's currently so few people that de-duping is easy by hand.

**Comment by aaronkaplan** [comment]
See https://github.com/certtools/intelmq-manager/pull/204
