### ISSUE TITLE
Create Bots via IntelMQ Manager

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq-manager#21]

**Comment by wagner-certat** [comment]
We do have many generic collectors and some generic parsers, which can be widely used (they actually show replace more other parsers), and are configurable by parameters. Is a UI for creating new bots really useful?

**Comment by wagner-certat** [comment]
I did not unassign @mauroasilva but I also can't reassign :/

**Comment by aaronkaplan** [comment]
Because @mauroasilva needs to accept the admin invite link for the repo.

**Comment by wagner-certat** [comment]
unclear what is being requested here
