### ISSUE TITLE
Duplicated BOT in Management

### ISSUE THREAD

**Issue by giedriusramas** [certtools/intelmq-manager#211]
intelmq manager version 2.2.0
We are experiencing  weird behavior of intelmq manager. 

### Expected behavior
Unique BOT ID is shown in bot status

### Actual behavior

![image](https://user-images.githubusercontent.com/8708094/94902330-a554ab00-04a0-11eb-9ab2-41d6f80186ea.png)

### Tried actions
- restart apache
- clean browser cache

https://intelmq.url/php/controller.php?scope=botnet&action=status&group=botnet returns 
``` 

{"ASN-Lookup-Expert": "running", "ASN-Lookup-Expert-1": "running", "AntiDDoS-Parser": "running" }
```

**Comment by wagner-certat** [comment]
Are all bot duplicated from the initial loading of the page on, or only after an automatic refresh (every 3 seconds)?

**Comment by wagner-certat** [comment]
@e3rd Maybe you have an idea?

**Comment by giedriusramas** [comment]
> Are all bot duplicated from the initial loading of the page on, or only after an automatic refresh (every 3 seconds)?
We observed issue after rebooting virtual machine(where intelmq and intelmqmanager is hosted). The strange thing is that issue just gone after some time.

**Comment by e3rd** [comment]
1. Just gone? You mean the superfluous bots just disappeared?
2. So you were not trying to duplicate the bots, they just appeared?

**Comment by wagner-certat** [comment]
Not reproducible
