### ISSUE TITLE
Debian packages usability: webserver not required, causing missing webserver configuration

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq-manager#246]
When installing intelmq-manager via deb packages, the user will be faced with two challenges:
- installing intelmq-manager does not pull in the required intelmq-api
- installing intelmq-manager without having apache already preinstalled, does not pull in apache by itself and does not enable the configuration:
https://github.com/certtools/intelmq-manager/blob/387b039681454d74516b778691ad23b22a06db45/debian/intelmq-manager.postinst#L5-L8
Therefore installing intelmq-api or apache2 after installing intelmq-manager, will result in `/etc/apache2/conf-enabled/intelmq-manager.conf` not existing and requires a re-configuration or re-installation of the package.

See also the threads https://lists.cert.at/pipermail/intelmq-users/2021-March/000233.html and https://lists.cert.at/pipermail/intelmq-users/2021-March/000221.html on the mailinglist

**Comment by ghost** [comment]
This was fixed in bd8c698
