### ISSUE TITLE
DOM text reinterpreted as HTML in static.js on lines 433 and 128

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq-manager#268]
GitHub's CodeQL detected two possible (medium-severity) security issues:

https://github.com/certtools/intelmq-manager/blob/92f726aa674620d354cb08b5d055ee38a7539d07/intelmq_manager/static/js/static.js#L433-L433
and
https://github.com/certtools/intelmq-manager/blob/92f726aa674620d354cb08b5d055ee38a7539d07/intelmq_manager/static/js/static.js#L128-L128
Both with:
> DOM text is reinterpreted as HTML without escaping meta-characters.

**Comment by monoidic** [comment]
Fixed by #270
