### ISSUE TITLE
Potential Client-side cross-site scripting in monitor.js lines 291 and 413 and static.js line 128

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq-manager#269]
GitHub's CodeQL found three potential (medium-severity) issues with Client-side cross-site scripting

- https://github.com/certtools/intelmq-manager/blob/92f726aa674620d354cb08b5d055ee38a7539d07/intelmq_manager/static/js/monitor.js#L291-L291
- https://github.com/certtools/intelmq-manager/blob/92f726aa674620d354cb08b5d055ee38a7539d07/intelmq_manager/static/js/static.js#L128-L128
- https://github.com/certtools/intelmq-manager/blob/92f726aa674620d354cb08b5d055ee38a7539d07/intelmq_manager/static/js/monitor.js#L314-L314
> Cross-site scripting vulnerability due to user-provided value

**Comment by monoidic** [comment]
Fixed by #270
