### ISSUE TITLE
Adding queues for newly added bots requires reload

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq-manager#280]
1. Add a new bot
2. Add a (destination) queue
3. Save

The destination queue is not saved, can be verified with a reload of the page.

Adding a queue to a previously existing bot works.

**Comment by monoidic** [comment]
This appears to stem from the same underlying issue as #279

**Comment by monoidic** [comment]
Seems fixed to me as of #281?

**Comment by ghost** [comment]
True, that works now for me.
