### ISSUE TITLE
504 error 

### ISSUE THREAD

**Issue by mikkster** [certtools/intelmq-manager#284]
Once I have made changes to the configuration file and saved changes I receive a 504 error with the following message 
```
[REDACTED] - - [18/Jan/2022:17:16:52 +0000] "GET /intelmq/v1/api/debug HTTP/1.1" 504 184 "http://{REDACTED}/configs.html" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" "-"
```
```
17:22:34 Get an error error, Gateway Time-out when trying to obtain config file properly
```

Any assistant with this would be great

**Comment by sebix** [comment]
What does the error log say? (`/var/log/apache2/error.log`)? Which OS do you use? How did you install the IntelMQ Manager/API?

**Comment by sebix** [comment]
Timeout.
