### ISSUE TITLE
Login failed with unknown reason. Please report this bug.

### ISSUE THREAD

**Issue by qasidali1** [certtools/intelmq-manager#288]
When I start the collectors. For sometime it work fine. But after sometime it keeps on loading. When tried Logout and login. Show this error.

**Comment by sebix** [comment]
How did you install IntelMQ and which operating system do you use?

Can you please open the developer tools (Ctrl+Shift+I), switch to the network tab, load or the page triggering the error and paste the response of the request `/intelmq/v1/api/login`?
Does the error log of your webserver show anything?

**Comment by qasidali1** [comment]
I am using ubuntu.
Using the docker Image.
I just tried creating the docker image again it works.
For now I have not get this error again.

**Comment by sebix** [comment]
Thanks for sharing your observation. If it happens again, the information I mentioned above would be helpful.

cc @waldbauer-certat because of Docker

**Comment by qasidali1** [comment]
Sure I'll
I am playing with this now a days.

**Comment by qasidali1** [comment]
Request URL: http://127.0.0.1:1337/intelmq/v1/api/login
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://127.0.0.1:1337/
sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest



Again got the same error
This  I got from Network tab

**Comment by sebix** [comment]
That's the request from the browser, not the response from the server.

Did the webserver logs show anything in the error log?

**Comment by qasidali1** [comment]
Thanks for your support I got the issue it was with my docker.


I have another confusion.
I am getting the events file but in events file ioc are missing. Where I can find the ioc.?
