### ISSUE TITLE
Incorrect URL when saving configuration

### ISSUE THREAD

**Issue by gethvi** [certtools/intelmq-manager#290]
When saving new configuration via manager, the POST request is made to this URLpath: `/v1/api//runtime` (note the double slash) which results in 404. The following lines are the culprit:

https://github.com/certtools/intelmq-manager/blob/affb7cec87de211823426ae97bb9623e9de538d8/intelmq_manager/static/js/intelmq-manager.js#L24-L29

https://github.com/certtools/intelmq-manager/blob/affb7cec87de211823426ae97bb9623e9de538d8/intelmq_manager/static/js/configs.js#L243

The same goes for `/v1/api//positions`:

https://github.com/certtools/intelmq-manager/blob/affb7cec87de211823426ae97bb9623e9de538d8/intelmq_manager/static/js/configs.js#L247

**Comment by gethvi** [comment]
Removing the extra slash from `configs.js` seems to fix the issue. It shouldn't brake anything else I believe.

**Comment by sebix** [comment]
Which web server do you use? Any special configuration?

**Comment by gethvi** [comment]
Nginx. Custom configuration, but nothing special:
```
location /intelmq/v1/api {
    proxy_pass http://intelmq:8080;
    include /etc/nginx/conf.d/internal_hosts;
    deny all;
}

location / {
    root /var/www/intelmq/;
    include /etc/nginx/conf.d/internal_hosts;
    deny all;
}
```

I modified intelmq-api sources and added this line to `serve.py`:
```python
api.http.base_url = '/intelmq'
```

Therefore the full URLpath in my case is `/intelmq/v1/api//runtime`. (Based on the ROOT variable in javascript, I had another issue with this, because the API wouldn't accept requests starting with /intelmq. I realize that changing the ROOT might have been the better approach.)

I don't believe this should be causing the issue as the URLpath concatenation is done entirely in javascript. Also every other URL is working fine.

**Comment by sebix** [comment]
> I don't believe this should be causing the issue as the URLpath concatenation is done entirely in javascript. Also every other URL is working fine.

Yeah, but I'd expect that the server doesn't care. Neither nginx or hug.
The default webserver for the intelmq-api is apache, maybe that behaves differently in regards to URL sanitation.

**Comment by gethvi** [comment]
I believe hug cares, because the request was passed (proxied) by the nginx correctly to the hug and hug responded with 404.

If Apache does this kind of sanitation the application shouldn't depend on it.

**Comment by sebix** [comment]
> If Apache does this kind of sanitation the application shouldn't depend on it.

I agree with you on this, of course. The app should handle double-slashes properly anyway.
