### ISSUE TITLE
intelmq-certbund install error

### ISSUE THREAD

**Issue by kodebrain** [certtools/intelmq-manager#291]
> Installation of intelmq and intelmq-manager successful

> login to the intelmq-manager, create a sample feed, and output to PostgreSQL working ok

> Issue occurs after installing certbund, at this point, the application stops working
` intelmqctl status
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==3.0.2', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'intelmq.bin'`

**Comment by kodebrain** [comment]
> https://github.com/Intevation/intelmq-certbund-contact
ran the setup.py install

`running install
running bdist_egg
running egg_info
writing intelmq_certbund_contact.egg-info/PKG-INFO
writing dependency_links to intelmq_certbund_contact.egg-info/dependency_links.txt
writing entry points to intelmq_certbund_contact.egg-info/entry_points.txt
writing requirements to intelmq_certbund_contact.egg-info/requires.txt
writing top-level names to intelmq_certbund_contact.egg-info/top_level.txt
reading manifest file 'intelmq_certbund_contact.egg-info/SOURCES.txt'
writing manifest file 'intelmq_certbund_contact.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/intelmq_certbund_contact
copying build/lib/intelmq_certbund_contact/init.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact
creating build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe
copying build/lib/intelmq_certbund_contact/ripe/init.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe
copying build/lib/intelmq_certbund_contact/ripe/ripe_diff.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe
copying build/lib/intelmq_certbund_contact/ripe/ripe_data.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe
copying build/lib/intelmq_certbund_contact/ripe/ripe_import.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe
copying build/lib/intelmq_certbund_contact/common.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact
copying build/lib/intelmq_certbund_contact/annotations.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact
copying build/lib/intelmq_certbund_contact/rulesupport.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact
copying build/lib/intelmq_certbund_contact/eventjson.py -> build/bdist.linux-x86_64/egg/intelmq_certbund_contact
creating build/bdist.linux-x86_64/egg/intelmq
copying build/lib/intelmq/init.py -> build/bdist.linux-x86_64/egg/intelmq
creating build/bdist.linux-x86_64/egg/intelmq/bots
copying build/lib/intelmq/bots/init.py -> build/bdist.linux-x86_64/egg/intelmq/bots
creating build/bdist.linux-x86_64/egg/intelmq/bots/experts
creating build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_rules
copying build/lib/intelmq/bots/experts/certbund_rules/init.py -> build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_rules
copying build/lib/intelmq/bots/experts/certbund_rules/expert.py -> build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_rules
copying build/lib/intelmq/bots/experts/init.py -> build/bdist.linux-x86_64/egg/intelmq/bots/experts
creating build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_contact
copying build/lib/intelmq/bots/experts/certbund_contact/init.py -> build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_contact
copying build/lib/intelmq/bots/experts/certbund_contact/expert.py -> build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_contact
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe/ripe_diff.py to ripe_diff.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe/ripe_data.py to ripe_data.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/ripe/ripe_import.py to ripe_import.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/common.py to common.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/annotations.py to annotations.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/rulesupport.py to rulesupport.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq_certbund_contact/eventjson.py to eventjson.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_rules/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_rules/expert.py to expert.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/experts/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_contact/init.py to init.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/intelmq/bots/experts/certbund_contact/expert.py to expert.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.8/ripe_download -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.8/import-national-certs -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/ripe_download to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/import-national-certs to 775
copying intelmq_certbund_contact.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying intelmq_certbund_contact.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying intelmq_certbund_contact.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying intelmq_certbund_contact.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying intelmq_certbund_contact.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying intelmq_certbund_contact.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/intelmq_certbund_contact-0.9.7-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing intelmq_certbund_contact-0.9.7-py3.8.egg
Removing /usr/local/lib/python3.8/dist-packages/intelmq_certbund_contact-0.9.7-py3.8.egg
Copying intelmq_certbund_contact-0.9.7-py3.8.egg to /usr/local/lib/python3.8/dist-packages
intelmq-certbund-contact 0.9.7 is already the active version in easy-install.pth
Installing import-national-certs script to /usr/local/bin
Installing ripe_download script to /usr/local/bin
Installing intelmq.bots.experts.certbund_contact.expert script to /usr/local/bin
Installing intelmq.bots.experts.certbund_rules.expert script to /usr/local/bin
Installing ripe_diff script to /usr/local/bin
Installing ripe_import script to /usr/local/bin

Installed /usr/local/lib/python3.8/dist-packages/intelmq_certbund_contact-0.9.7-py3.8.egg
Processing dependencies for intelmq-certbund-contact==0.9.7
Searching for psycopg2==2.9.5
Best match: psycopg2 2.9.5
Adding psycopg2 2.9.5 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for intelmqmail==1.3.0
Best match: intelmqmail 1.3.0
Processing intelmqmail-1.3.0-py3.8.egg
intelmqmail 1.3.0 is already the active version in easy-install.pth
Installing intelmqcbmail script to /usr/local/bin

Using /usr/local/lib/python3.8/dist-packages/intelmqmail-1.3.0-py3.8.egg
Searching for intelmq==3.0.2
Best match: intelmq 3.0.2
Adding intelmq 3.0.2 to easy-install.pth file
Installing intelmq.bots.collectors.alienvault_otx.collector script to /usr/local/bin
Installing intelmq.bots.collectors.amqp.collector_amqp script to /usr/local/bin
Installing intelmq.bots.collectors.api.collector_api script to /usr/local/bin
Installing intelmq.bots.collectors.blueliv.collector_crimeserver script to /usr/local/bin
Installing intelmq.bots.collectors.calidog.collector_certstream script to /usr/local/bin
Installing intelmq.bots.collectors.eset.collector script to /usr/local/bin
Installing intelmq.bots.collectors.file.collector_file script to /usr/local/bin
Installing intelmq.bots.collectors.fireeye.collector_mas script to /usr/local/bin
Installing intelmq.bots.collectors.github_api.collector_github_contents_api script to /usr/local/bin
Installing intelmq.bots.collectors.http.collector_http script to /usr/local/bin
Installing intelmq.bots.collectors.http.collector_http_stream script to /usr/local/bin
Installing intelmq.bots.collectors.kafka.collector script to /usr/local/bin
Installing intelmq.bots.collectors.mail.collector_mail_attach script to /usr/local/bin
Installing intelmq.bots.collectors.mail.collector_mail_body script to /usr/local/bin
Installing intelmq.bots.collectors.mail.collector_mail_url script to /usr/local/bin
Installing intelmq.bots.collectors.microsoft.collector_azure script to /usr/local/bin
Installing intelmq.bots.collectors.microsoft.collector_interflow script to /usr/local/bin
Installing intelmq.bots.collectors.misp.collector script to /usr/local/bin
Installing intelmq.bots.collectors.opendxl.collector script to /usr/local/bin
Installing intelmq.bots.collectors.rsync.collector_rsync script to /usr/local/bin
Installing intelmq.bots.collectors.rt.collector_rt script to /usr/local/bin
Installing intelmq.bots.collectors.shadowserver.collector_reports_api script to /usr/local/bin
Installing intelmq.bots.collectors.shodan.collector_stream script to /usr/local/bin
Installing intelmq.bots.collectors.stomp.collector script to /usr/local/bin
Installing intelmq.bots.collectors.tcp.collector script to /usr/local/bin
Installing intelmq.bots.collectors.twitter.collector_twitter script to /usr/local/bin
Installing intelmq.bots.experts.abusix.expert script to /usr/local/bin
Installing intelmq.bots.experts.aggregate.expert script to /usr/local/bin
Installing intelmq.bots.experts.asn_lookup.expert script to /usr/local/bin
Installing intelmq.bots.experts.csv_converter.expert script to /usr/local/bin
Installing intelmq.bots.experts.cymru_whois.expert script to /usr/local/bin
Installing intelmq.bots.experts.deduplicator.expert script to /usr/local/bin
Installing intelmq.bots.experts.do_portal.expert script to /usr/local/bin
Installing intelmq.bots.experts.domain_suffix.expert script to /usr/local/bin
Installing intelmq.bots.experts.field_reducer.expert script to /usr/local/bin
Installing intelmq.bots.experts.filter.expert script to /usr/local/bin
Installing intelmq.bots.experts.format_field.expert script to /usr/local/bin
Installing intelmq.bots.experts.generic_db_lookup.expert script to /usr/local/bin
Installing intelmq.bots.experts.geohash.expert script to /usr/local/bin
Installing intelmq.bots.experts.gethostbyname.expert script to /usr/local/bin
Installing intelmq.bots.experts.http.expert_content script to /usr/local/bin
Installing intelmq.bots.experts.http.expert_status script to /usr/local/bin
Installing intelmq.bots.experts.idea.expert script to /usr/local/bin
Installing intelmq.bots.experts.lookyloo.expert script to /usr/local/bin
Installing intelmq.bots.experts.maxmind_geoip.expert script to /usr/local/bin
Installing intelmq.bots.experts.mcafee.expert_mar script to /usr/local/bin
Installing intelmq.bots.experts.misp.expert script to /usr/local/bin
Installing intelmq.bots.experts.modify.expert script to /usr/local/bin
Installing intelmq.bots.experts.national_cert_contact_certat.expert script to /usr/local/bin
Installing intelmq.bots.experts.rdap.expert script to /usr/local/bin
Installing intelmq.bots.experts.recordedfuture_iprisk.expert script to /usr/local/bin
Installing intelmq.bots.experts.reverse_dns.expert script to /usr/local/bin
Installing intelmq.bots.experts.rfc1918.expert script to /usr/local/bin
Installing intelmq.bots.experts.ripe.expert script to /usr/local/bin
Installing intelmq.bots.experts.sieve.expert script to /usr/local/bin
Installing intelmq.bots.experts.sieve.validator script to /usr/local/bin
Installing intelmq.bots.experts.splunk_saved_search.expert script to /usr/local/bin
Installing intelmq.bots.experts.taxonomy.expert script to /usr/local/bin
Installing intelmq.bots.experts.threshold.expert script to /usr/local/bin
Installing intelmq.bots.experts.tor_nodes.expert script to /usr/local/bin
Installing intelmq.bots.experts.trusted_introducer_lookup.expert script to /usr/local/bin
Installing intelmq.bots.experts.tuency.expert script to /usr/local/bin
Installing intelmq.bots.experts.url2fqdn.expert script to /usr/local/bin
Installing intelmq.bots.experts.uwhoisd.expert script to /usr/local/bin
Installing intelmq.bots.experts.wait.expert script to /usr/local/bin
Installing intelmq.bots.outputs.amqptopic.output script to /usr/local/bin
Installing intelmq.bots.outputs.blackhole.output script to /usr/local/bin
Installing intelmq.bots.outputs.elasticsearch.output script to /usr/local/bin
Installing intelmq.bots.outputs.file.output script to /usr/local/bin
Installing intelmq.bots.outputs.files.output script to /usr/local/bin
Installing intelmq.bots.outputs.mcafee.output_esm_ip script to /usr/local/bin
Installing intelmq.bots.outputs.misp.output_api script to /usr/local/bin
Installing intelmq.bots.outputs.misp.output_feed script to /usr/local/bin
Installing intelmq.bots.outputs.mongodb.output script to /usr/local/bin
Installing intelmq.bots.outputs.postgresql.output script to /usr/local/bin
Installing intelmq.bots.outputs.redis.output script to /usr/local/bin
Installing intelmq.bots.outputs.restapi.output script to /usr/local/bin
Installing intelmq.bots.outputs.rt.output script to /usr/local/bin
Installing intelmq.bots.outputs.smtp.output script to /usr/local/bin
Installing intelmq.bots.outputs.sql.output script to /usr/local/bin
Installing intelmq.bots.outputs.stomp.output script to /usr/local/bin
Installing intelmq.bots.outputs.tcp.output script to /usr/local/bin
Installing intelmq.bots.outputs.templated_smtp.output script to /usr/local/bin
Installing intelmq.bots.outputs.touch.output script to /usr/local/bin
Installing intelmq.bots.outputs.udp.output script to /usr/local/bin
Installing intelmq.bots.parsers.abusech.parser_domain script to /usr/local/bin
Installing intelmq.bots.parsers.abusech.parser_ip script to /usr/local/bin
Installing intelmq.bots.parsers.alienvault.parser script to /usr/local/bin
Installing intelmq.bots.parsers.alienvault.parser_otx script to /usr/local/bin
Installing intelmq.bots.parsers.anubisnetworks.parser script to /usr/local/bin
Installing intelmq.bots.parsers.autoshun.parser script to /usr/local/bin
Installing intelmq.bots.parsers.bambenek.parser script to /usr/local/bin
Installing intelmq.bots.parsers.blocklistde.parser script to /usr/local/bin
Installing intelmq.bots.parsers.blueliv.parser_crimeserver script to /usr/local/bin
Installing intelmq.bots.parsers.calidog.parser_certstream script to /usr/local/bin
Installing intelmq.bots.parsers.cert_eu.parser_csv script to /usr/local/bin
Installing intelmq.bots.parsers.ci_army.parser script to /usr/local/bin
Installing intelmq.bots.parsers.cleanmx.parser script to /usr/local/bin
Installing intelmq.bots.parsers.cymru.parser_cap_program script to /usr/local/bin
Installing intelmq.bots.parsers.cymru.parser_full_bogons script to /usr/local/bin
Installing intelmq.bots.parsers.cznic.parser_haas script to /usr/local/bin
Installing intelmq.bots.parsers.cznic.parser_proki script to /usr/local/bin
Installing intelmq.bots.parsers.danger_rulez.parser script to /usr/local/bin
Installing intelmq.bots.parsers.dataplane.parser script to /usr/local/bin
Installing intelmq.bots.parsers.dshield.parser_asn script to /usr/local/bin
Installing intelmq.bots.parsers.dshield.parser_block script to /usr/local/bin
Installing intelmq.bots.parsers.dshield.parser_domain script to /usr/local/bin
Installing intelmq.bots.parsers.dyn.parser script to /usr/local/bin
Installing intelmq.bots.parsers.eset.parser script to /usr/local/bin
Installing intelmq.bots.parsers.fireeye.parser script to /usr/local/bin
Installing intelmq.bots.parsers.fraunhofer.parser_dga script to /usr/local/bin
Installing intelmq.bots.parsers.generic.parser_csv script to /usr/local/bin
Installing intelmq.bots.parsers.github_feed.parser script to /usr/local/bin
Installing intelmq.bots.parsers.hibp.parser_callback script to /usr/local/bin
Installing intelmq.bots.parsers.html_table.parser script to /usr/local/bin
Installing intelmq.bots.parsers.json.parser script to /usr/local/bin
Installing intelmq.bots.parsers.key_value.parser script to /usr/local/bin
Installing intelmq.bots.parsers.malc0de.parser script to /usr/local/bin
Installing intelmq.bots.parsers.malwarepatrol.parser_dansguardian script to /usr/local/bin
Installing intelmq.bots.parsers.malwareurl.parser script to /usr/local/bin
Installing intelmq.bots.parsers.mcafee.parser_atd script to /usr/local/bin
Installing intelmq.bots.parsers.microsoft.parser_bingmurls script to /usr/local/bin
Installing intelmq.bots.parsers.microsoft.parser_ctip script to /usr/local/bin
Installing intelmq.bots.parsers.misp.parser script to /usr/local/bin
Installing intelmq.bots.parsers.n6.parser_n6stomp script to /usr/local/bin
Installing intelmq.bots.parsers.netlab_360.parser script to /usr/local/bin
Installing intelmq.bots.parsers.openphish.parser script to /usr/local/bin
Installing intelmq.bots.parsers.openphish.parser_commercial script to /usr/local/bin
Installing intelmq.bots.parsers.phishtank.parser script to /usr/local/bin
Installing intelmq.bots.parsers.shadowserver.parser script to /usr/local/bin
Installing intelmq.bots.parsers.shadowserver.parser_json script to /usr/local/bin
Installing intelmq.bots.parsers.shodan.parser script to /usr/local/bin
Installing intelmq.bots.parsers.spamhaus.parser_cert script to /usr/local/bin
Installing intelmq.bots.parsers.spamhaus.parser_drop script to /usr/local/bin
Installing intelmq.bots.parsers.sucuri.parser script to /usr/local/bin
Installing intelmq.bots.parsers.surbl.parser script to /usr/local/bin
Installing intelmq.bots.parsers.taichung.parser script to /usr/local/bin
Installing intelmq.bots.parsers.threatminer.parser script to /usr/local/bin
Installing intelmq.bots.parsers.turris.parser script to /usr/local/bin
Installing intelmq.bots.parsers.twitter.parser script to /usr/local/bin
Installing intelmq.bots.parsers.vxvault.parser script to /usr/local/bin
Installing intelmq.bots.parsers.webinspektor.parser script to /usr/local/bin
Installing intelmq.bots.parsers.zoneh.parser script to /usr/local/bin
Installing intelmq_psql_initdb script to /usr/local/bin
Installing intelmqctl script to /usr/local/bin
Installing intelmqdump script to /usr/local/bin
Installing intelmqsetup script to /usr/local/bin

Using /usr/lib/python3/dist-packages
Searching for gpg==1.10.0
Best match: gpg 1.10.0
Processing gpg-1.10.0-py3.8-linux-x86_64.egg
gpg 1.10.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.8/dist-packages/gpg-1.10.0-py3.8-linux-x86_64.egg
Finished processing dependencies for intelmq-certbund-contact==0.9.7`

**Comment by sebix** [comment]
Sorry, I completely missed your message here.

Could you let me know if you were able to fix the issue?
