### ISSUE TITLE
The meaning of "Live" and "Physics"

### ISSUE THREAD

**Issue by qux-bbb** [certtools/intelmq-manager#297]
Hi, I'm confused about meaning of "Live" and "Physics".  

When toggled "Live" and "Physics" and clicked "Redraw Botnet", I found "Physics" means that all nodes and edges have physical effects, but I still don't know the meaning of "Live".  

Is that right about my explanation of Physics? Is there someone can explain the meaning of "Live"?  

Thanks

**Comment by sebix** [comment]
Hi @qux-bbb 

With `Live` enabled you should see how many messages are queued for processing per each bot. The counters are automatically refreshed every second or so.

For Physics, your assumptions are correct, it enables the physics engine with bouncing effects, with bots acting like repulsive magnets

**Comment by qux-bbb** [comment]
I get it. Thank you!
