### ISSUE TITLE
Configurations files permissions

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq-manager#46]
If the unix ownership of /opt/intelmq/etc/* is not set to intelmq:intelmq (with proper perms 0644), then intelmq-manager will say "yes, I 'll save your config" when the user presses "save" . However, it has not feedback if the save operation succeeded. In the case of wrong ownership/perms, it did not succeed.

Need to fix the user experience here.

**Comment by sebix** [comment]
Duplicate of #69
