### ISSUE TITLE
Load __default__ section from runtime.conf

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq-manager#47]
Since the new feature from intelmq regarding the default configurations in runtime.conf, its necessary to update intelmq-manager.

**Comment by SYNchroACK** [comment]
Commit: https://github.com/certtools/intelmq/commit/940e6ad9fed00a7edc2163474ad57bf37fb657b2

**Comment by SYNchroACK** [comment]
...waiting... :P

**Comment by mauroasilva** [comment]
Done
