### ISSUE TITLE
Clear a queue

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq-manager#54]
In certtools/intelmq#244

> Therefore I would suggest to have a clear command in intelmqctl and **a "clear queue" button in the "monitor"-tab of the Manager.**

intelmqctl-part is implemented by certtools/intelmq#277, the UI part missing.

**Comment by aaronkaplan** [comment]
is this OK now in the UI? I did not see it fixed yet (in the UI).

**Comment by sebix** [comment]
It's not implemented yet, thus the issue is still open here.

**Comment by wagner-certat** [comment]
See also certtools/intelmq#1068

**Comment by wagner-certat** [comment]
fixed by 7b55d34ea30049948c03718508106dd587862342
