### ISSUE TITLE
Error JSON - Impossible to see data in Monitor page

### ISSUE THREAD

**Issue by danje57** [certtools/intelmq-manager#64]
Hi,

I've istalled the last versio of IntelMQ and IntelMQ Manager on a Centos using Python 3.4.

Everything works excepting that I can't see the Logs on the Manager.

Each time I tried to see the logs I've this error:

    Error loading bot logs: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

I've created botnet using the manager, I created bots, all bots start normally.

All files are created on `/opt/intelmq/var/log`.

But when I try to see the content using the manager I've the error of JSON parsing file.

Could you help me to investigate this issue?

Regards,

**Comment by mauroasilva** [comment]
Hi,

Can you check if you have the intelmqctl version that by default outputs nothing to stdout please?

There was a version of intelmqctl that outputed only to a log file and the manager expects the ctl to print to stdout. Login into a shell with the webserver user and run the command that is specified on the config.php and check if it outputs something please.

**Comment by danje57** [comment]
Hi Maurosilva,

Following your idea,

I gone into the config.php file

There is a command:

sudo -u intelmq /opt/intelmq/bin/intelmqctl %s

I've copied this line.

Then I gone on another shell and prompt:

su - intelmq
sudo -u intelmq /opt/intelmq/bin/intelmqctl %s

and the command told me that intelmq user is not on the sudoers file.

However, I made the change on the sudoers file as I added:

apache ALL=(intelmq) NOPASSWD: /opt/intelmq/bin/intelmqctl

I've also configurer in the sudoers the line
Defaults         requiretty
to
Defaults        !requiretty

:-/

**Comment by danje57** [comment]
However all other functionnality run well.

logged using intelmq user I can start, stop, botnet, botid

su - intelmq
intelmqctl --botnet start
....

**Comment by mauroasilva** [comment]
That means the problem is with sudo itself. 

Try doing:
```
sudo -u apache bash -c 'sudo -u intelmq /opt/intelmq/bin/intelmqctl'
```

To see if the apache user can sudo to the intelmq user and run the intelmqctl.

**Comment by danje57** [comment]
your command above works,
intelmqctl command is displayed

so I've to modify the line on config.php with your command?

regards

**Comment by danje57** [comment]
I tried to replace the command from php.ini by:

$CONTROLLER = "sudo -u apache bash -c 'sudo -u intelmq /opt/intelmq/bin/intelmqctl %s'"

But it doesn't work, now I've json parser error on the Management page and always the same on the monitor page.

I revert back to the original $CONTROLLER syntax.

**Comment by danje57** [comment]
I followed this to configure intelmq manager:

yum install git httpd php
systemctl enable httpd
systemctl start httpd

git clone https://github.com/certtools/intelmq-manager.git /tmp/intelmq-manager
cp -R /tmp/intelmq-manager/intelmq-manager/* /var/www/html
chown -R root.root /var/www/html/

Fix /etc/sudoers after configure properly:
sed -i 's|Defaults    requiretty|Defaults    !requiretty|g' /etc/sudoers

usermod -a -G intelmq apache

echo "apache ALL=(intelmq) NOPASSWD: /opt/intelmq/bin/intelmqctl" >> /etc/sudoers

sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python3.4|g' /opt/intelmq/bin/intelmqctl
sed -i 's|SELINUX=enforcing|SELINUX=disabled|g' /etc/selinux/config

firewall-cmd --add-service http
firewall-cmd --add-service http --permanent

reboot

**Comment by danje57** [comment]
And thes steps for intelmq server:


yum install epel-release
yum install python34 python34-devel
yum install git libcurl-devel gcc gcc-c++
yum install redis

Install the last pip version:

curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
python3.4 /tmp/get-pip.py

Enable redis on startup:

systemctl enable redis
systemctl start redis



git clone https://github.com/certtools/intelmq.git /tmp/intelmq
cd /tmp/intelmq

sudo -s

pip3 install -r REQUIREMENTS
python3.4 setup.py install

useradd -d /opt/intelmq -U -s /bin/bash intelmq
echo 'export PATH="$PATH:$HOME/bin"' > /opt/intelmq/.profile
chmod -R 0770 /opt/intelmq
chown -R intelmq.intelmq /opt/intelmq
echo 'export INTELMQ_PYTHON=/usr/bin/python3.4' >> /opt/intelmq/.profile

**Comment by danje57** [comment]
I've checked error log on httpd:

I've this:

Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks

**Comment by aaronkaplan** [comment]
could this be a python3.4 issue?

Did you try running it with python 2.7?

**Comment by danje57** [comment]
No I'll try with Python 2.7 now.

**Comment by aaronkaplan** [comment]
> On 08 Jan 2016, at 12:41, danje57 <notifications@github.com> wrote:
> 
> No I'll try with Python 2.7 now.

Thanks! This will help to narrow down the problem.

**Comment by danje57** [comment]
I tried on CentOS using minimal install
I had an error compilation
openssh failed
gcc failed

when I tried this line
pip2 install -r REQUIREMENTS2

Now I'll try on debian

**Comment by aaronkaplan** [comment]
> On 08 Jan 2016, at 13:04, danje57 <notifications@github.com> wrote:
> 
> I tried on CentOS using minimal install
> I had an error compilation
> openssh failed
> gcc failed
> 
> when I tried this line
> pip2 install -r REQUIREMENTS2
> 
> Now I'll try on debian


Yes, we only tested on Ubuntu and Debian. I guess we'll have to look at CentOS again.
Thanks for taking the time to help us to debug.

**Comment by danje57** [comment]
Now I've installed debian.

I've the same bug

When I execute this line:
pip3 install -r REQUIREMENTS

I have

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-50xz01s9/pycurl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fmq0cg1i-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-50xz01s9/pycurl
Storing debug log for failure in /root/.pip/pip.log

Now I'll try debian using python 2.7

Luckilly I use snapshot :-)

**Comment by danje57** [comment]
Same error on Debian 8, using Python 2.7

pip2 install -r REQUIREMENTS


compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Can't roll back pycurl; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZMpJwx/pycurl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JOn8eL-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-ZMpJwx/pycurl
Storing debug log for failure in /root/.pip/pip.log

**Comment by danje57** [comment]
I'll try Ubunto now...

**Comment by aaronkaplan** [comment]
> On 08 Jan 2016, at 13:18, danje57 <notifications@github.com> wrote:
> 
> I'll try Ubunto now...

wait wait I think this will be the same... Debian/Ubuntu are very similar.

Need to be able to reproduce the bug that you are seeing.
Maybe there is some dependency missing?

Did you install build-essentials in Debian?

Best,
a.

**Comment by danje57** [comment]
Yes I follow, Installation instruction:

apt-get install python3 python3-pip
apt-get install git build-essential libcurl4-gnutls-dev libffi-dev
apt-get install redis-server

**Comment by danje57** [comment]
I'm building a Ubuntu machine.

It's not to long on my vmware

**Comment by aaronkaplan** [comment]
> On 08 Jan 2016, at 13:29, danje57 <notifications@github.com> wrote:
> 
> I'm building a Ubuntu machine.
> 
> It's not to long on my vmware

okay. Thx

**Comment by danje57** [comment]
On Ubuntu, I've the same thing when installing PIP REQUIREMENTS

---------
compilation terminated.
    ***************************************************************************
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.
    ***************************************************************************

    warning: no files found matching 'requirements.txt'
    ***************************************************************************
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python build succeeded.
    ***************************************************************************
Successfully i
----------------

However message is sucess at the end :-/ 
Will try the rest of the installation

**Comment by danje57** [comment]
Ok I've just finish on ubuntu.

I can finish the installation of IntelMq and IntelMq manager.

However I've the same error in the Monitor page:

Error loading bot logs: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Does people test the last version of IntelMQ here ? :-p

**Comment by danje57** [comment]
If you have time to test it in your side I'm curious to know your result.

However I'll try to send data to ArcSight using output node

**Comment by danje57** [comment]
On Ubuntu I tried to replace the $CONTROLLER variable by
sudo -u apache bash -c 'sudo -u intelmq /opt/intelmq/bin/intelmqctl %s'

But the result is that I've JSON error on each manager page....

**Comment by aaronkaplan** [comment]
> On 08 Jan 2016, at 14:12, danje57 <notifications@github.com> wrote:
> 
> On Ubuntu I tried to replace the $CONTROLLER variable by
> sudo -u apache bash -c 'sudo -u intelmq /opt/intelmq/bin/intelmqctl %s'
> 
> But the result is that I've JSON error on each manager page....

It's weird. I think Mauro needs to answer this one.

**Comment by danje57** [comment]
Hope he can help

**Comment by mauroasilva** [comment]
Sorry for the delay, I've been configuring a machine to reproduce your steps exactly as you described them for CentOS. I'm doing some tests and the first thing I noticed is that the regex you use on sed didn't change the "Defaults requiretty" on my machine. I have to replace it with:

```
sed -i 's|Defaults.*requiretty|Defaults !requiretty|g' /etc/sudoers
```

Can you confirm if the requiretty is actually changed please?

**Comment by mauroasilva** [comment]
As soon as I did the sed everything started to work.

**Comment by danje57** [comment]
Ok thx, I'll try this now!!! :-)

**Comment by danje57** [comment]
It doesn't work for me. Always the same Json message error.

IntelMQ server:

I installed all as root user.

--------------------
yum install epel-release
yum install python34 python34-devel
yum install git libcurl-devel gcc gcc-c++
yum install redis

Install the last pip version:

curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
python3.4 /tmp/get-pip.py

Enable redis on startup:

systemctl enable redis
systemctl start redis

git clone https://github.com/certtools/intelmq.git /tmp/intelmq
cd /tmp/intelmq

sudo -s

pip3 install -r REQUIREMENTS
python3.4 setup.py install

useradd -d /opt/intelmq -U -s /bin/bash intelmq
echo 'export PATH="$PATH:$HOME/bin"' > /opt/intelmq/.profile
chmod -R 0770 /opt/intelmq
chown -R intelmq.intelmq /opt/intelmq
echo 'export INTELMQ_PYTHON=/usr/bin/python3.4' >> /opt/intelmq/.profile
--------------------

Then I installed IntelMq Manager as root too

--------------------
yum install git httpd php
systemctl enable httpd
systemctl start httpd

git clone https://github.com/certtools/intelmq-manager.git /tmp/intelmq-manager
cp -R /tmp/intelmq-manager/intelmq-manager/* /var/www/html
chown -R root.root /var/www/html/

Fix /etc/sudoers after configure properly:
sed -i 's|Defaults.*requiretty|Defaults !requiretty|g' /etc/sudoers

usermod -a -G intelmq apache

echo "apache ALL=(intelmq) NOPASSWD: /opt/intelmq/bin/intelmqctl" >> /etc/sudoers

sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python3.4|g' /opt/intelmq/bin/intelmqctl

sed -i 's|SELINUX=enforcing|SELINUX=disabled|g' /etc/selinux/config

firewall-cmd --add-service http
firewall-cmd --add-service http --permanent

reboot
--------------------


Then I started IntelMQ server as intelmq user:

-----------------
su - intelmq
intelmqctl --botnet start


This all steps I made

**Comment by mauroasilva** [comment]
Can you please send me (mauro.a.silva@gmail.com) the apache error logs of your server so I can debug? And can you also check if the !requiretty is actually in the sudoers file?

**Comment by danje57** [comment]
Yes of course!

This is the extract of the Apache Error file:

---------------------
[Wed Jan 06 14:58:38.369588 2016] [suexec:notice] [pid 13368] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00557: httpd: apr_sockaddr_info_get() failed for intelmq.localdomain
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
[Wed Jan 06 14:58:38.389872 2016] [auth_digest:notice] [pid 13368] AH01757: generating secret for digest authentication ...
[Wed Jan 06 14:58:38.390328 2016] [lbmethod_heartbeat:notice] [pid 13368] AH02282: No slotmem from mod_heartmonitor
[Wed Jan 06 14:58:38.408810 2016] [mpm_prefork:notice] [pid 13368] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Wed Jan 06 14:58:38.408849 2016] [core:notice] [pid 13368] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jan 06 15:03:22.372045 2016] [mpm_prefork:notice] [pid 13368] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jan 11 08:55:32.208917 2016] [suexec:notice] [pid 1088] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00557: httpd: apr_sockaddr_info_get() failed for intelmq.localdomain
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 11 08:55:32.238864 2016] [auth_digest:notice] [pid 1088] AH01757: generating secret for digest authentication ...
[Mon Jan 11 08:55:32.239347 2016] [lbmethod_heartbeat:notice] [pid 1088] AH02282: No slotmem from mod_heartmonitor
[Mon Jan 11 08:55:32.281795 2016] [mpm_prefork:notice] [pid 1088] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Mon Jan 11 08:55:32.281848 2016] [core:notice] [pid 1088] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
intelmqctl: Log path not found: /opt/intelmq/var/log/file-output.log
intelmqctl: Log path not found: /opt/intelmq/var/log/malware-domain-list-collector.log
intelmqctl: Log path not found: /opt/intelmq/var/log/malware-domain-list-parser.log
intelmqctl: Log path not found: /opt/intelmq/var/log/file-output.log
intelmqctl: Log path not found: /opt/intelmq/var/log/file-output.log
intelmqctl: Log path not found: /opt/intelmq/var/log/malware-domain-list-collector.log
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks
Traceback (most recent call last):
  File "/opt/intelmq/bin/intelmqctl", line 541, in <module>
    x.run()
  File "/opt/intelmq/bin/intelmqctl", line 278, in run
    results = self.read_log(self.args.log, self.args.bot_id)
  File "/opt/intelmq/bin/intelmqctl", line 490, in read_log
    return self.read_bot_log(bot_id, log_level, number_of_lines)
  File "/opt/intelmq/bin/intelmqctl", line 508, in read_bot_log
    for line in utils.reverse_readline(bot_log_path):
  File "/usr/lib/python3.4/site-packages/intelmq-1.0.0-py3.4.egg/intelmq/lib/utils.py", line 260, in reverse_readline
    handle.seek(-offset, os.SEEK_END)
io.UnsupportedOperation: can't do nonzero end-relative seeks
---------------------

My sudoers file:

---------------------
## Sudoers allows particular users to run various commands as
## the root user, without needing the root password.
##
## Examples are provided at the bottom of the file for collections
## of related commands, which can then be delegated out to particular
## users or groups.
##
## This file must be edited with the 'visudo' command.

## Host Aliases
## Groups of machines. You may prefer to use hostnames (perhaps using
## wildcards for entire domains) or IP addresses instead.
# Host_Alias     FILESERVERS = fs1, fs2
# Host_Alias     MAILSERVERS = smtp, smtp2

## User Aliases
## These aren't often necessary, as you can use regular groups
## (ie, from files, LDAP, NIS, etc) in this file - just use %groupname
## rather than USERALIAS
# User_Alias ADMINS = jsmith, mikem


## Command Aliases
## These are groups of related commands...

## Networking
# Cmnd_Alias NETWORKING = /sbin/route, /sbin/ifconfig, /bin/ping, /sbin/dhclient, /usr/bin/net, /sbin/iptables, /usr/bin/rfcomm, /usr/bin/wvdial, /sbin/iwconfig, /sbin/mii-tool

## Installation and management of software
# Cmnd_Alias SOFTWARE = /bin/rpm, /usr/bin/up2date, /usr/bin/yum

## Services
# Cmnd_Alias SERVICES = /sbin/service, /sbin/chkconfig

## Updating the locate database
# Cmnd_Alias LOCATE = /usr/bin/updatedb

## Storage
# Cmnd_Alias STORAGE = /sbin/fdisk, /sbin/sfdisk, /sbin/parted, /sbin/partprobe, /bin/mount, /bin/umount

## Delegating permissions
# Cmnd_Alias DELEGATING = /usr/sbin/visudo, /bin/chown, /bin/chmod, /bin/chgrp

## Processes
# Cmnd_Alias PROCESSES = /bin/nice, /bin/kill, /usr/bin/kill, /usr/bin/killall

## Drivers
# Cmnd_Alias DRIVERS = /sbin/modprobe

# Defaults specification
#
# Disable "ssh hostname sudo <cmd>", because it will show the password in clear.
#         You have to run "ssh -t hostname sudo <cmd>".
#
Defaults !requiretty

#
# Refuse to run if unable to disable echo on the tty. This setting should also be
# changed in order to be able to use sudo without a tty. See requiretty above.
#
Defaults   !visiblepw

#
# Preserving HOME has security implications since many programs
# use it when searching for configuration files. Note that HOME
# is already set when the the env_reset option is enabled, so
# this option is only effective for configurations where either
# env_reset is disabled or HOME is present in the env_keep list.
#
Defaults    always_set_home

Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"

#
# Adding HOME to env_keep may enable a user to run unrestricted
# commands via sudo.
#
# Defaults   env_keep += "HOME"

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin

## Next comes the main part: which users can run what software on
## which machines (the sudoers file can be shared between multiple
## systems).
## Syntax:
##
##      user    MACHINE=COMMANDS
##
## The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allows members of the 'sys' group to run networking, software,
## service management apps and more.
# %sys ALL = NETWORKING, SOFTWARE, SERVICES, STORAGE, DELEGATING, PROCESSES, LOCATE, DRIVERS
## Allows people in group wheel to run all commands
%wheel  ALL=(ALL)       ALL

## Same thing without a password
# %wheel        ALL=(ALL)       NOPASSWD: ALL

## Allows members of the users group to mount and unmount the
## cdrom as root
# %users  ALL=/sbin/mount /mnt/cdrom, /sbin/umount /mnt/cdrom

## Allows members of the users group to shutdown this system
# %users  localhost=/sbin/shutdown -h now

## Read drop-in files from /etc/sudoers.d (the # here does not mean a comment)
#includedir /etc/sudoers.d
apache ALL=(intelmq) NOPASSWD: /opt/intelmq/bin/intelmqctl

---------------------

Hope it help.

**Comment by mauroasilva** [comment]
Clarify something for me...

With that install you can see the configuration and management menus without a problem, but you then get an error on the monitor. Is that it?

**Comment by danje57** [comment]
that's correct.

I can use all option from the interface. Excepted the monitor sheet.

Each time I've the JSON error :-/

**Comment by mauroasilva** [comment]
That makes sense if you never started the bots before. What it is trying to do is access the log file of the bots and the log file doesn't exist because you never started the bots.

**Comment by mauroasilva** [comment]
The code could probably be a bit easier to figure out, you're right... the error message doesn't lead you to conclude that the problem is that there are no log files. I'll try to change it a bit.

**Comment by danje57** [comment]
Yes.
But i dont understand why the json error appears.
As you can saw on the error log it seem that intelmqctl isused by apache when i use the monitor page. But it issues some error

**Comment by mauroasilva** [comment]
Yes, what happens is that everything that you see in the intelmq-manager is actually a call to the intelmqctl so that we don't have the same features implemented in two different places. What is happening is that when you open the monitor tab and click any of the bots, it calls intelmqctl to ask for the logs of that bot. intelmqctl tries to access the log file and since the bot never created a log file, intelmqctl does not return anything, which makes the manager try to parse an empty string as a JSON object and fails with that error.

**Comment by aaronkaplan** [comment]
I think the manager could then say something like "no Data" or so. 
That would be more intuitive IMHO. 
What do you think?

---
Mobile

**Comment by danje57** [comment]
Unfortunately its not the good reason. Indeed my log file are populated correctly in /opt/intelmq/.../logs.
So the server works well. The issue come from manager call

**Comment by mauroasilva** [comment]
Nice... apparently you found a bug in intelmqctl. Just tested the code that reads the log files and from Python 3.2 forward, non-binary files can't have relative seeks from the end of the file. Which means we will have to change intelmqctl.

Thanks a lot for the find ;)

**Comment by danje57** [comment]
Ahhhh ok!!!!
I thought I was suly!!!

Ok, I'll check the source code tomorrow and try to make a fix... if I can understand the code correctly of course :-)

**Comment by mauroasilva** [comment]
Closed because this is actually an IntelMQ bug.

**Comment by aaronkaplan** [comment]
> On 12 Jan 2016, at 16:11, mauroasilva <notifications@github.com> wrote:
> 
> Closed because this is actually an IntelMQ bug.

Then let's re=open it there?

**Comment by sebix** [comment]
Duplicate of certtools/intelmq#393
fix is on the way
