### ISSUE TITLE
I have a  bounced error in management page,how to solve it?

### ISSUE THREAD

**Issue by Hacker-One** [certtools/intelmq-manager#67]
when I click the start ,then bounce an error ![pic](https://cloud.githubusercontent.com/assets/14013299/14135413/e3296f8e-f68f-11e5-8828-de6dede1904e.jpg)

**Comment by sebix** [comment]
Execute `intelmqctl -n status` and `intelmqctl -b start -i [bot-id-you-want to start]` as user intelmq and show the output please.

**Comment by Hacker-One** [comment]
> # intelmqctl -n status
intelmqctl: abusech-zeus-tracker-ips-collector is stopped.
intelmqctl: abusech-zeus-tracker-ips-parser is stopped.
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.
# intelmqctl -b start -i malware-domain-list-collector
intelmqctl: Starting malware-domain-list-collector...
intelmqctl: malware-domain-list-collector is running.
# intelmqctl -b start -i malware-domain-list-parser
intelmqctl: Starting malware-domain-list-parser...
intelmqctl: malware-domain-list-parser is running.
# intelmqctl -b start -i file-output
intelmqctl: Starting file-output...
intelmqctl: file-output is running.
# intelmqctl -n status
intelmqctl: abusech-zeus-tracker-ips-collector is stopped.
intelmqctl: abusech-zeus-tracker-ips-parser is stopped.
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.

>

**Comment by sebix** [comment]
Mh. Two problems here.

The bots all terminate after starting. I guess the directories `/opt/intelmq/var/log` and `/opt/intelmq/var/lib/bots/file-ouput` do not exist (fix is in pull request certtools/intelmq#465).

We still do not know what the manager is complaining about. By adding `-t json` to the commands we can see what the manager calls. Otherwise it's probably a permission/sudoers issue (Try calling `sudo -u intelmq /usr/local/bin/intelmqctl ...` as user www-data).

**Comment by Hacker-One** [comment]
`intelmq$ intelmqctl -n status`
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.
`intelmq$ intelmqctl -b start -i malware-domain-list-collector`
intelmqctl: Starting malware-domain-list-collector...
intelmqctl: malware-domain-list-collector is running.
`intelmq$ intelmqctl -b start -i malware-domain-list-parser`
intelmqctl: Starting malware-domain-list-parser...
intelmqctl: malware-domain-list-parser is running.
`intelmq$ intelmqctl -b start -i file-output`
intelmqctl: Starting file-output...
intelmqctl: file-output is running.
`intelmq$ intelmqctl -n status`
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.
`intelmq$ python3 -m intelmq.bots.outputs.file.output file-output`
file-output: FileBot initialized with id file-output and version 3.4.3 (default, Oct 14 2015, 20:28:29).
file-output: Loading defaults configuration.
file-output: Defaults configuration: parameter 'accuracy' loaded  with value '100'.
file-output: Defaults configuration: parameter 'http_verify_cert' loaded  with value 'True'.
file-output: Defaults configuration: parameter 'logging_handler' loaded  with value 'file'.
file-output: Defaults configuration: parameter 'error_dump_message' loaded  with value 'True'.
file-output: Defaults configuration: parameter 'load_balance' loaded  with value 'False'.
file-output: Defaults configuration: parameter 'source_pipeline_db' loaded  with value '2'.
file-output: Defaults configuration: parameter 'destination_pipeline_host' loaded  with value '127.0.0.1'.
file-output: Defaults configuration: parameter 'source_pipeline_host' loaded  with value '127.0.0.1'.
file-output: Defaults configuration: parameter 'error_retry_delay' loaded  with value '15'.
file-output: Defaults configuration: parameter 'http_ssl_proxy' loaded  with value 'None'.
file-output: Defaults configuration: parameter 'source_pipeline_port' loaded  with value '6379'.
file-output: Defaults configuration: parameter 'broker' loaded  with value 'redis'.
file-output: Defaults configuration: parameter 'destination_pipeline_port' loaded  with value '6379'.
file-output: Defaults configuration: parameter 'http_proxy' loaded  with value 'None'.
file-output: Defaults configuration: parameter 'error_max_retries' loaded  with value '3'.
file-output: Defaults configuration: parameter 'error_log_message' loaded  with value 'True'.
file-output: Defaults configuration: parameter 'logging_syslog' loaded  with value '/dev/log'.
file-output: Defaults configuration: parameter 'error_procedure' loaded  with value 'pass'.
file-output: Defaults configuration: parameter 'rate_limit' loaded  with value '0'.
file-output: Defaults configuration: parameter 'error_log_exception' loaded  with value 'True'.
file-output: Defaults configuration: parameter 'http_user_agent' loaded  with value 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'.
file-output: Defaults configuration: parameter 'destination_pipeline_db' loaded  with value '2'.
file-output: Loading system configuration
file-output: System configuration: parameter 'logging_path' loaded  with value '/opt/intelmq/var/log/'.
file-output: System configuration: parameter 'logging_level' loaded  with value 'DEBUG'.
file-output: Bot is starting.
file-output: Loading runtime configuration
file-output: Runtime configuration: parameter 'file' loaded with value '/opt/intelmq/var/lib/bots/file-output/events.txt'.
file-output: Loading pipeline configuration
file-output: Pipeline configuration: parameter 'source-queue' loaded with the value 'file-output-queue'.
file-output: Loading Harmonization configuration.
file-output: Opening /opt/intelmq/var/lib/bots/file-output/events.txt file
file-output: File /opt/intelmq/var/lib/bots/file-output/events.txt is open.
file-output: Bot starts processings.
file-output: Loading source pipeline.
file-output: Loading source queue.
file-output: Source queue loaded file-output-queue.
file-output: Connected to source queue.
file-output: Loading destination pipeline.
file-output: Loading destination queues.
file-output: Destination queues loaded None.
file-output: Connected to destination queues.
file-output: Pipeline ready.
file-output: Start processing.
file-output: Receiving Message.

this is my result,but all bots  don't runn.I don't know why it's that?

**Comment by sebix** [comment]
Hm, do the pids in `/opt/intelmq/var/run/` contain correct pids?

**Comment by Hacker-One** [comment]
intelmq@virtual-machine:~/var/run$ intelmqctl -n status
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.
intelmq@virtual-machine:~/var/run$ ls -al
总用量 20
drwxr-xr-x 2 intelmq intelmq 4096  3月 30 20:51 .
drwxrwx--- 5 intelmq intelmq 4096  3月 30 18:36 ..
-rw-rw-r-- 1 intelmq intelmq    5  3月 30 18:58 file-output.pid
-rw-rw-r-- 1 intelmq intelmq    4  3月 30 20:45 malware-domain-list-collector.pid
-rw-rw-r-- 1 intelmq intelmq    5  3月 30 18:58 malware-domain-list-parser.pid
intelmq@virtual-machine:~/var/run$ intelmqctl -b start -i malware-domain-list-collector
intelmqctl: Starting malware-domain-list-collector...
intelmqctl: malware-domain-list-collector is running.
intelmq@virtual-machine:~/var/run$ intelmqctl -n status
intelmqctl: file-output is stopped.
intelmqctl: malware-domain-list-collector is stopped.
intelmqctl: malware-domain-list-parser is stopped.


Still can't,  Does it need to do `sudo chown -R intelmq.intelmq  /usr/local/bin`?

**Comment by sebix** [comment]
> Still can't,  Does it need to do `sudo chown -R intelmq.intelmq  /usr/local/bin`?

No.

Which OS do you use? Will try to reproduce it, but that will take some time.

**Comment by Hacker-One** [comment]
ubuntu 14.04  python3.
I intelmq-manager is OK.I can start all bots,but have a question that these bots will change from running to stopped when I click management.html again.

**Comment by Hacker-One** [comment]
I guess it is intelmq caused,like the above problem .  
all bots look like running in the management.html,but do command `intelmqctl -n status` ,all bots are stopped

**Comment by sebix** [comment]
Yes, it's not the manager, it's either intelmqctl or the bots. Are the processes running? (started via intelmqctl - I guess yes)

**Comment by Hacker-One** [comment]
intelmq@virtual-machine:/home/diver$ ps aux | grep intelmq
root       2078  0.0  0.3  70824  3604 pts/8    S    21:55   0:00 su intelmq
intelmq    2079  0.0  0.3  25276  3804 pts/8    S    21:55   0:00 bash
intelmq    2089  0.0  0.2  22648  2568 pts/8    R+   21:57   0:00 ps aux
intelmq    2090  0.0  0.2  15960  2228 pts/8    S+   21:57   0:00 grep intelmq

**Comment by Hacker-One** [comment]
intelmq@virtual-machine:/home/diver$ ps aux | grep intelmq
root       2078  0.0  0.3  70824  3604 pts/8    S    21:55   0:00 su intelmq
intelmq    2079  0.0  0.3  25276  3804 pts/8    S    21:55   0:00 bash
intelmq    2089  0.0  0.2  22648  2568 pts/8    R+   21:57   0:00 ps aux
intelmq    2090  0.0  0.2  15960  2228 pts/8    S+   21:57   0:00 grep intelmq

**Comment by Hacker-One** [comment]
Don't have intelmqctl process...

**Comment by Hacker-One** [comment]
"Are the processes running? "  ---what's this about processes?

**Comment by sebix** [comment]
intelmqctl itself does always terminate, it spawns the bots as independent processes. But those do not exist.

To summarize:
Bots do terminate immediately, if started via intelmq-manager.
Bots do terminate immediately, if started via intelmqctl as user www-data and sudo.
Bots do terminate immediately, if started via intelmqctl as user intelmq.
Bots are running, if started as python module directly (`python -m`).

Hm. Something strange is going on.

**Comment by Hacker-One** [comment]
Thank you very much!  I understand.

but all bots aren't running,i don't know why...

**Comment by mauroasilva** [comment]
Hacker-One do you see any error on the apache logs?

**Comment by pedromreis** [comment]
Had the same "symptoms".
Running RHEL 7.2, nginx, python3.4
fixed it with:

in /etc/sudoers (on the appropriate sections)
	Defaults    !requiretty 
	Defaults    env_keep += "INTELMQ_PYTHON"
	nginx ALL=(intelmq) NOPASSWD: /usr/bin/intelmqctl *

in /opt/intelmq/html/php/config.php 
        $CONTROLLER = "sudo INTELMQ_PYTHON=/usr/bin/python3.4 -u intelmq /usr/bin/intelmqctl %s";

**Comment by sebix** [comment]
The `env_keep` the modification of `$CONTROLLER` should not be necessary with PR certtools/intelmq#469 anymore.

I documented the sudoers rule for nginx in 990f97dc4325c448e5923004bc0fc7da01d247e4

**Comment by Hacker-One** [comment]
I already deal with this question used python2.7.
thank you!

But i have a new question:
I execute `intelmqctl -n start `that all bots are running in terminal,but some bots don't run when I operate through intelmq-manager. Can you help me?

**Comment by Hacker-One** [comment]
I have resolved this questiong.
I ignore the permission.
Thanks!
