### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq-manager#69]
Currently, when the manager talks to the ctl tool and an error occurs, the only message the user gets is a JSON-parse error message. The message box should show the complete output in order to examine the problem.

**Comment by aaronkaplan** [comment]
BTW: I think I am getting error messages all the time in the monitor page. No idea why yet...

**Comment by aaronkaplan** [comment]
add to this: if there is a permission error for save.php, the script shall tell the user what the problem is and not just stay quiet and not save the data.

**Comment by wagner-certat** [comment]
possible errors:
- php/controller.php returns nothing, `"error"`, `Invalid scope` or not valid JSON
- php/save.php returns nothing, `Invalid bot ID`, `Config has invalid characters`, `Could not write file.` or `same content`
- php/load_configs.php returns nothing
