### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by CERT-Bund** [certtools/intelmq-manager#77]
Monitoring changes (e.g. Log Level, Records per Page and Paging) in intelq-manager 20160519.1~rc1 has no effect on the display of logs.

**Comment by sebix** [comment]
We are not doing releases, so there is no `20160519.1~rc1`. Maybe you refer to this fork: https://github.com/Intevation/intelmq-manager

Works with current master (the bug has been fixed in 5f5373e331b345f9a00fa4c1cd57583b22bd0811 on 2016-05-03)

**Comment by dmth** [comment]
@Sebix Our 20160519.1~rc1 contains your https://github.com/certtools/intelmq-manager/commit/5f5373e331b345f9a00fa4c1cd57583b22bd0811 so this issue should not appear. Nevertheless: We will test with latest intelmq-manager from certtools and report if the issue still exists.

**Comment by sebix** [comment]
@ondj discovered that the order was not correct, a thing which I apparently overlooked (even in the manager it seems), with certtools/intelmq-manager#78 I hope this issue is solved now.

**Comment by dmth** [comment]
Tested with latest master, seems to work now.
