### ISSUE TITLE
Support for data types

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq-manager#81]
Currently the manager does only support strings. I.e. if you provide some value in the edit boxes in the intelmq manager, it will treat everything as string. Even if actually by the definiton of the the Data Harmonisation Ontology (DHO) it should be an int or a Bool or something else.
In other words: the manager (or intelmqctl) should check for correct types against the DHO.

Needed types:
- [x] Integers and Floats
- [x] Boolean
- [x] null/None
- [x] lists
- [x] dict
- [x] ~possibly raw json?~

**Comment by wagner-certat** [comment]
The manager does replace a dictionary with `"[object Object]"`. We can show some json-representation to the user which will be converted back at save.

**Comment by e3rd** [comment]
What's the difference between `raw json` and a `dict`? `List` and `dict` will be indeed supported in #174 , I checked them out.

**Comment by wagner-certat** [comment]
No idea^^
I removed it

**Comment by wagner-certat** [comment]
Was fixed in 1.2.0
