### ISSUE TITLE
Allow a link between a collector and an output bot

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq-manager#84]
I wanted to connect a collector bot directly with an output bot without going through a parser first, but the IntelMQ Manager did not allow me to do this. I received the following alert:
![screen shot 2016-09-22 at 17 03 18](https://cloud.githubusercontent.com/assets/2568336/18753718/7febc372-80e6-11e6-81a8-3cc1f7d41d2a.png)

I initially thought this was because IntelMQ did not allow it, but it is possible if you manually edit the `pipeline.conf` file. The IntelMQ Manager will then also show it correctly afterwards. 

( @aaronkaplan: This is the issue I also mentioned to you yesterday)

**Comment by sebix** [comment]
See [static.js](https://github.com/certtools/intelmq-manager/blob/2d491dd5ac9075a5791f367222023a0cd3bbe7cd/intelmq-manager/js/static.js#L3)
