### ISSUE TITLE
Show "enabled" switch

### ISSUE THREAD

**Issue by sykaeh** [certtools/intelmq-manager#92]
It would be great to be able to control the "enabled" switch (see certtools/intelmq#715) in the configuration and also show the status in the management tab.

**Comment by wagner-certat** [comment]
It's already possible to do that in the configuration, see #98

**Comment by aaronkaplan** [comment]
@sykaeh did you mean a graphical on/off checkbox?

**Comment by wagner-certat** [comment]
fixed in #98
