### ISSUE TITLE
Getting "Error loading botnet status: SyntxError: Unexpected end of JSON input" on WebUI

### ISSUE THREAD

**Issue by espressobeanie** [certtools/intelmq-manager#93]
Hi,

After following the Ubuntu instructions for IntelMQ and IntelMQ-Manager, I get the following error when selecting Management and Monitoring tabs:

Error loading botnet status: SyntxError: Unexpected end of JSON input

Thoughts?

**Comment by sebix** [comment]
Which OS do you use?

What is the output of `sudo -u www-data sudo -u intelmq /usr/local/bin/intelmqctl status --type=json`?


Also see #63 #64 #66 #67

**Comment by espressobeanie** [comment]
It showed all the bots stopped. I solved the issue. The www-data permissions weren't in the /etc/sudoers file. Thank you Sebix. :)
