### ISSUE TITLE
master branch seems to be broken for 88f276b

### ISSUE THREAD

**Issue by gulung** [certtools/intelmq-manager#95]
Hello.

I am trying to install latest versions of bot intelmq and intelmq-manager as described in the docs.
```
    1  apt update; apt -y dist-upgrade
    2  apt install python3 python3-pip git build-essential libffi-dev python3-dev redis-server
    3  pip3 install typing
    4  ls
    5  git clone https://github.com/certtools/intelmq.git /tmp/intelmq
    6  cd /tmp/intelmq
    7  pip3 install -r REQUIREMENTS
    8  pip3 .
    9  pip3 install --upgrade pip
   10  pip3 install .
   11  useradd -d /opt/intelmq -U -s /bin/bash intelmq
   12  chmod -R 0770 /opt/intelmq
   13  chown -R intelmq.intelmq /opt/intelmq
   14  cd /opt/intelmq/etc
   15  cp -a examples/* .
   16  intelmqctl restart
   17  intelmqctl status
   18  apt install git apache2 php libapache2-mod-php7.0
   19  git clone https://github.com/certtools/intelmq-manager.git /tmp/intelmq-manager
   20  cp -R /tmp/intelmq-manager/intelmq-manager/* /var/www/html/
   21  chown -R www-data.www-data /var/www/html/
   22  usermod -a -G intelmq www-data
   23  chgrp www-data /opt/intelmq/etc/*.conf
   24  chmod g+w /opt/intelmq/etc/*.conf
   25  echo "www-data ALL=(intelmq) NOPASSWD: /usr/local/bin/intelmqctl" >> /etc/sudoers
   26  cat /etc/sudoers
   27  nano /var/www/html/php/config.php 
   28  /etc/init.d/apache2 restart
   29  nano /var/www/html/php/config.php 
   30  cat ~/.bash_history
   31  cd
   32  ls
   33  ls -la
   34  history
```

And I get an error that has already been discussed in https://github.com/certtools/intelmq-manager/issues/67 https://github.com/certtools/intelmq-manager/issues/66 https://github.com/certtools/intelmq-manager/issues/64

 and should have been resolved 

![screenshot from 2017-02-24 20-22-45](https://cloud.githubusercontent.com/assets/26010696/23315625/1e499cae-fad8-11e6-9107-b9f87181ba25.png)
![screenshot from 2017-02-24 20-23-28](https://cloud.githubusercontent.com/assets/26010696/23315666/3f2af756-fad8-11e6-91b0-750ccde1b2e2.png)

```
intelmq@ubuntu:~$ intelmqctl status
intelmqctl: abusech-domain-parser is running.
intelmqctl: abusech-feodo-domains-collector is running.
intelmqctl: cymru-whois-expert is running.
intelmqctl: deduplicator-expert is running.
intelmqctl: file-output is running.
intelmqctl: gethostbyname-1-expert is running.
intelmqctl: gethostbyname-2-expert is running.
intelmqctl: malc0de-parser is running.
intelmqctl: malc0de-windows-format-collector is running.
intelmqctl: malware-domain-list-collector is running.
intelmqctl: malware-domain-list-parser is running.
intelmqctl: spamhaus-drop-collector is running.
intelmqctl: spamhaus-drop-parser is running.
intelmqctl: taxonomy-expert is running.
intelmqctl: url2fqdn-expert is running.
```
```
intelmq@ubuntu:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

I guess somebody should fix this

**Comment by gulung** [comment]
@SYNchroACK @sebix @wagner-certat

**Comment by gulung** [comment]
https://github.com/certtools/intelmq/issues/393 https://github.com/certtools/intelmq/pull/435

**Comment by gulung** [comment]
Configuration section of intelmq-manager and all the features of intelmq seem to work perfectly. Great work, I like this instrument 👍

**Comment by mohl1** [comment]
I have the same issue. After the installation (based on install guide) I get the same error. 
Looked at the config.php file. If i change the CONTROLLER part in the config.php file to:

$CONTROLLER = "sudo -u intelmq /usr/local/bin/intelmqctl %s"; 
I can open the configuration page. **NOT** the Management and Monitor page (same error as mentioned above).

if I change it to:
$CONTROLLER = "sudo -u intelmq /usr/local/bin/intelmqctl --type json %s";
I can open every page without an error. However when I try to start a BOT I get the error: _"Error starting bot: SyntaxError: Unexpected end of JSON input"_

I can start the BOT via intelmqctl without any problems and can see in IntelMQ Management that the BOT is started. Seems that I cannot start or stop a BOT via IntelMQ Manager.

Have you seen the same issue? Any ideas how to overcome?
Thanks,

**Comment by gulung** [comment]
@mohl1 A patch is needed for this. For the `start`, `stop` and other actions like that the command has to be `intelmqctl start` and `intelmqctl --json start` fails.
I am wondering how it ended up in master branch.

**Comment by wagner-certat** [comment]
@gulung If `intelmqctl --type json start` fails for you, your intelmq installation is not up to date.

**Comment by wagner-certat** [comment]
@mohl1 Can you show the output of these commands please?

```bash
> sudo -u www-data sudo -u intelmq /usr/local/bin/intelmqctl --type json status
> sudo -u www-data sudo -u intelmq /usr/local/bin/intelmqctl --type json start bot-id
```
and replace bot-id with an existing bot's ID. According to your problem description, the first command fails while the second does not.

**Comment by wagner-certat** [comment]
no feedback, closing this.
