### ISSUE TITLE
Error loading botnet status: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by empereor** [certtools/intelmq-manager#97]
When trying to view the Management or Monitor pages, I get the error in the subject.

Details:
RHEL7
`-bash-4.2$ intelmqctl -v`
`1.0.0.dev6`
Installed as documented here, mod'd for RHEL:
https://github.com/certtools/intelmq-manager/blob/master/docs/INSTALL.md

`yum install git httpd`
`sudo su -`
`git clone https://github.com/certtools/intelmq-manager.git /tmp/intelmq-manager`
`cp -R /tmp/intelmq-manager/intelmq-manager/* /var/www/html/`
`chown -R apache.apache /var/www/html/`
`usermod -a -G intelmq apache`
`chgrp apache /opt/intelmq/etc/*.conf`
`chmod g+w /opt/intelmq/etc/*.conf`

Added to sudoers:
`apache ALL=(intelmq) NOPASSWD: /usr/bin/intelmqctl`

Added to /var/www/html/php/config.php:
`$CONTROLLER = "sudo -u intelmq /usr/bin/intelmqctl --type json %s";`

`chcon -R -t httpd_sys_content_t /var/www/html`
`semanage fcontext -a -t httpd_sys_content_t "/var/www/html(/.*)?"`

Verified log file perms:
`# ls -al /opt/intelmq/var/log/intelmqctl.log`
`-rw-rw-r--. 1 intelmq intelmq 27274 Mar  1 14:48 /opt/intelmq/var/log/intelmqctl.log`

Verified output file perms:
`#  ls -al /opt/intelmq/var/lib/bots/file-output/`
`total 364`
`drwxrwx---. 2 intelmq intelmq     24 Mar  1 13:31 .`
`drwxrwx---. 3 intelmq intelmq     25 Mar  1 13:04 ..`
`-rw-r--r--. 1 intelmq intelmq 371106 Mar  1 13:31 events.txt`

Verified sudo:
`# sudo -u apache sudo -u intelmq /usr/bin/intelmqctl --type=json status`
`{"malware-domain-list-parser": "stopped", "malc0de-parser": "stopped", "url2fqdn-expert": "stopped", "malc0de-windows-format-collector": "stopped", "malware-domain-list-collector": "stopped", "spamhaus-drop-parser": "stopped", "abusech-domain-parser": "stopped", "gethostbyname-1-expert": "stopped", "file-output": "stopped", "abusech-feodo-domains-collector": "stopped", "deduplicator-expert": "stopped", "gethostbyname-2-expert": "stopped", "spamhaus-drop-collector": "stopped", "taxonomy-expert": "stopped", "cymru-whois-expert": "stopped"}`

Restart apache:
`# systemctl restart httpd.service`

`# su - intelmq`
`Last login: Wed Mar  1 14:43:40 EST 2017 on pts/0`
`-bash-4.2$ intelmqctl check`
`intelmqctl: Reading configuration files.`
`intelmqctl: Checking runtime configuration.`
`intelmqctl: Checking pipeline configuration.`
`intelmqctl: Checking for bots.`
`intelmqctl: No issues found.`
`-bash-4.2$`

`# systemctl status httpd.service -l`
`● httpd.service - The Apache HTTP Server`
`   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)`
`   Active: active (running) since Wed 2017-03-01 17:06:26 EST; 8min ago`
`     Docs: man:httpd(8)`
`           man:apachectl(8)`
`  Process: 27231 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=0/SUCCESS)`
` Main PID: 27237 (httpd)`
`   Status: "Total requests: 14; Current requests/sec: 0; Current traffic:   0 B/sec"`
`   CGroup: /system.slice/httpd.service`
`           ├─27237 /usr/sbin/httpd -DFOREGROUND`
`           ├─27238 /usr/sbin/httpd -DFOREGROUND`
`           ├─27239 /usr/sbin/httpd -DFOREGROUND`
`           ├─27240 /usr/sbin/httpd -DFOREGROUND`
`           ├─27241 /usr/sbin/httpd -DFOREGROUND`
`           ├─27242 /usr/sbin/httpd -DFOREGROUND`
`           ├─27245 /usr/sbin/httpd -DFOREGROUND`
`           ├─27247 /usr/sbin/httpd -DFOREGROUND`
`           └─27248 /usr/sbin/httpd -DFOREGROUND`
` `
`Mar 01 17:06:26 dev.xxxxx.com systemd[1]: Starting The Apache HTTP Server...`
`Mar 01 17:06:26 dev.xxxxx.com systemd[1]: Started The Apache HTTP Server. `
`Mar 01 17:10:27 dev.xxxxx.com sudo[27256]:   apache : TTY=unknown ; PWD=/var/www/html/php ; USER=intelmq ; COMMAND=/usr/bin/intelmqctl --type json list queues`
`Mar 01 17:10:41 dev.xxxxx.com sudo[27257]:   apache : TTY=unknown ; PWD=/var/www/html/php ; USER=intelmq ; COMMAND=/usr/bin/intelmqctl --type json status`

The management.html page never shows the botnet status and the monitor.html page just continually throws the error.

**Comment by empereor** [comment]
This is an SELinux issue. Closing.

**Comment by wagner-certat** [comment]
> This is an SELinux issue. Closing.

How did you fix it? I'd like to distribute the SELinux rules so others do not have these issues.

**Comment by mf370** [comment]
@empereor do you mind sharing how did you solve your issue with IntelMQ Manager? I followed your instructions and I'm having the same problem, but I can't figure out how to solve it! Thank you!
